services:
  product-service:
    build:
      context: ./services/product-service
    container_name: inventory-product-service
    ports:
      - "8081:8081"
    restart: unless-stopped

  inventory-service:
    build:
      context: ./services/inventory-service
    container_name: inventory-inventory-service
    ports:
      - "8082:8082"
    restart: unless-stopped
